# Generated by Django 3.2.16 on 2023-01-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahasiswa', models.CharField(max_length=20)),
                ('waktu', models.TimeField()),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'tb_absen',
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('namaDosen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_dosen',
            },
        ),
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_golongan',
            },
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeMK', models.CharField(max_length=20)),
                ('mataKuliah', models.CharField(max_length=50)),
                ('sks', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_matkul',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tb_users',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=20)),
                ('semester', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')])),
                ('telepon', models.CharField(max_length=14)),
                ('alamat', models.TextField(max_length=20)),
                ('jenisKelamin', models.TextField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')])),
                ('golongan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.golongan')),
            ],
            options={
                'db_table': 'tb_mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruangan', models.CharField(max_length=5)),
                ('hari', models.CharField(max_length=30)),
                ('jamMulai', models.TimeField()),
                ('jamSelesai', models.TimeField()),
                ('golongan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.golongan')),
                ('matkul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.matkul')),
                ('namaDosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.dosen')),
            ],
            options={
                'db_table': 'tb_jadwal',
            },
        ),
    ]
